# Generated by Django 5.0.7 on 2024-08-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bet_amount', models.IntegerField()),
                ('odds', models.FloatField()),
                ('payout', models.FloatField()),
                ('win', models.BooleanField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
