# Generated by Django 5.0.7 on 2024-08-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bets',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
